# 2.자연수와 행렬

## 2-1.수 체계

#### 코랩에서 한글 사용하기 위한 방법
- 한글 폰트 설치
- 코랩에서 [런타임 > 세션 다시 시작] 실행
- 그래프(matplotlib)에서 한글 폰트 지

In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

In [ ]:
import matplotlib.pyplot as plt

plt.rc('font', family='NanumBarunGothic')

### [실습] 수학의 분류
- 실행시 라이브러리 오류가 발생할 경우 해당 라이브러리를 설치 후 코드를 실행합니다.
- 라이브러리 설치 명령어 : %pip install plotly

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

# 파일 불러오기
filename = './수학의분류.csv'
category = pd.read_csv(filename)
category.head()

In [ ]:
category[ category['3단계 세부 주제'] == '정수론' ]

In [ ]:
print(category.columns)

In [ ]:
# 그래프 그리기
fig = px.treemap(data_frame=category,
                 path=[px.Constant('수학분류'),'1단계 분류', '2단계 분류', '3단계 세부 주제'],
                 values='가중치 (중요도)',
                 color='가중치 (중요도)',
                 color_continuous_scale='RdBu')
fig.update_traces(root_color="lightgrey")
fig.update_layout(title='수학의 분류', title_x=0.5)
fig.show()

### [실습] 수 체계 분류

In [ ]:
import math

def classify_number(num):
    try:
        # 복소수인지 확인
        if isinstance(num, complex):
            return f"{num:10}: 복소수 (Complex number)"

        # 실수인지 확인 (복소수 제외)
        if isinstance(num, float):
            if num.is_integer():
                return f"{num:10}: 정수 (Integer)"
            else:
                # 유리수인지 무리수인지 확인 (무리수는 직접 판별이 어려워, 유명한 무리수로 추정)
                if num in [math.pi, math.e, math.sqrt(2), math.sqrt(3)]:
                    return f"{num:10}: 무리수 (Irrational number)"
                else:
                    return f"{num:10}: 유리수 (Rational number)"

        # 정수인지 확인
        if isinstance(num, int):
            if num > 0:
                return f"{num:10}: 자연수 (Natural number)"
            else:
                return f"{num:10}: 정수 (Integer)"
    except Exception as e:
        return f"오류: {str(e)}"

# 테스트 케이스
print(classify_number(5))          # 자연수
print(classify_number(-3))         # 정수
print(classify_number(0))          # 정수
print(classify_number(0.5))        # 유리수
print(classify_number(math.pi))    # 무리수
print(classify_number(2 + 3j))     # 복소수
print(classify_number(math.sqrt(2))) # 무리수

-------------------

## 2-2.자연수와 정수

### [실습] 어떤 수가 정수인지 판단하는 프로그램

In [ ]:
# 정수 판별 프로그램
def is_integer(N):
    if N - int(N) == 0:
        print("정수")
    if N - int(N) != 0:
        print("소수")

try:
    N = input('숫자를 입력하세요: ')
    N = float(N)
    is_integer(N)
except ValueError:
    print("math error")

### [실습] 정수의 활용

**1. 카운팅과 순서**: 주어진 정수 리스트에서 짝수의 개수를 세고, 그 짝수의 인덱스를 반환하는 프로그램

In [ ]:
def count_even_numbers(lst):
    count = 0
    indices = []
    for i, num in enumerate(lst):
        if num % 2 == 0:
            count += 1
            indices.append(i)
    return count, indices

numbers = [3, 12, 5, 8, 14, 7, 2, 13]
count, indices = count_even_numbers(numbers)
print(f"짝수의 개수: {count}")
print(f"짝수의 위치: {indices}")

**2.금융에서의 잔고와 빚**: 주어진 거래 내역에서 잔고와 빚을 계산하고, 잔고가 음수가 되면 빚 리스트에 추가하는 프로그램

In [ ]:
def calculate_balance(transactions):
    balance = 0
    debts = []

    for amount in transactions:
        balance += amount
        if balance < 0:
            debts.append(balance)

    return balance, debts

transactions = [100, -150, 200, -50, -25, -300, 400]
final_balance, debts = calculate_balance(transactions)
print(f"최종 잔고: {final_balance} 만원")
print(f"빚 기록: {debts}")

**3. 좌표와 측정**: 두 점 (x1, y1)과 (x2, y2) 사이의 거리를 계산하는 프로그램

In [ ]:
import math

def calculate_distance(point1, point2):
    x1, y1 = point1
    x2, y2 = point2
    distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
    return distance

point1 = (-1, 2)
point2 = (3, 5)
distance = calculate_distance(point1, point2)
print(f"두 점 사이의 거리: {distance}")

**4. 수학적 연산**: 두 정수의 최대공약수와 최소공배수를 계산하는 프로그램

In [ ]:
def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a

def lcm(a, b):
    return abs(a * b) // gcd(a, b)

a = 60
b = 48
greatest_common_divisor = gcd(a, b)
least_common_multiple = lcm(a, b)

print(f"{a}와 {b}의 최대공약수: {greatest_common_divisor}")
print(f"{a}와 {b}의 최소공배수: {least_common_multiple}")

-------------------------------------

## 2-3.소수와 최대공약수

### [실습] : 어떤 수가 소수인가 판별하는 프로그램

In [ ]:
# 소수 판별하기
def is_prime_number1(x):
    for i in range(2, x):
        if x % i == 0 and x != i:
            return False # 소수가 아님
    return True          # 소수임

# 자연수 N을 입력한다.
x = int(input('\n소수 판별하기 위한 정수 값을 입력해 주세요 : '))
print('-'*50)
if is_prime_number1(x):
    print(f'{x} is prime number!!')
else:
    print(f'{x} is not prime number!!')


### [실습] : 개선된 소수판별 프로그램
- 제곱근 표시 : math.sqrt(x),   x**(1/2)

In [ ]:
import math

def is_prime_number2(x):
    for i in range(2, int(math.sqrt(x)) + 1):
#     for i in range(2, x**(1/2) + 1)
        if x % i == 0 and x != i:
            return False
    return True

# 자연수 N을 입력한다.
x = int(input('\n소수 판별하기 위한 정수 값을 입력해 주세요 : '))
print('-'*50)
if is_prime_number2(x):
    print(f'{x} is prime number!!')
else:
    print(f'{x} is not prime number!!')

### [실습] 최대공약수 구하기

In [ ]:
def greatest_common_divisor(a, b):
    while b != 0:
        a, b = b, a % b
    return a

a = 190
b = 34
print(f"{a}와 {b}의 최대공약수: {greatest_common_divisor(a, b)}")


### [실습] 암스트롱 수 구하기
- Armstrong Number(암스트롱 수)란 세자리의 자연수로 각 자리수의 세제곱의 합이 자기 자신의 수와  같은 수

In [ ]:
def is_amstrong_number(x):

    if x == int(str(x)[0])**3 + int(str(x)[1])**3 + int(str(x)[2])**3:
        return True
    else:
        return False


print('세 자리의 자연수인 암스트롱 수는: ')
for x in range(100, 1000, 1):
    if is_amstrong_number(x):
        print(x, end=' ')


-------------------------------

## 2-4.행렬의 개념과 행렬식

### 라이브러리 소개
- **numpy** : 고 성능 수치연산과 행렬식을 위한 라이브러리
- ndarray : n차원 배열 데이터 구조


In [ ]:
#!pip install numpy

### [실습] 행렬을 이용하여 연립방정식 풀기
5개의 빵과 2개의 우유를 사면 3000원을 지불해야하며, 10개의 빵과 3개의 우유를 사면 5000원을 지불해야 할때, 빵(x)과 우유(y) 각 1개씩의 가격은 얼마인가?


In [ ]:
import numpy as np

arr1 = np.array([[5,2],[10,3]])
arr2 = np.array([3000,5000])

result = np.linalg.solve(arr1, arr2) #행렬
print(result)         # 연립방정식 결과
print(result.dtype)   # 결과 data type

### [실생활에서 행렬이 사용된 예제] 이미지 처리

In [ ]:
!pip install opencv-python

In [ ]:
import cv2
cv2.__version__

In [ ]:
import sys
import numpy as np
import cv2
from google.colab.patches import cv2_imshow

src = cv2.imread('cat.jpg', cv2.IMREAD_GRAYSCALE)

if src is None:
    print('Image load failed!')
    sys.exit()

# 부드럽게
mask = np.array([[1/9,1/9,1/9],
                [1/9,1/9,1/9],
                [1/9,1/9,1/9]])
# mask = np.ones((3,3), dtype=np.float64)/ 9.

dst1 = cv2.filter2D(src, -1, mask) # 부드럽게


# 날카롭게
mask = np.array([[0,-1,0],
                [-1,4,-1],
                [0,-1,0]])

dst2 = cv2.filter2D(src, -1, mask) # 날카롭게

cv2_imshow(src)   #cv2.imshow('src', src)
cv2_imshow(dst1)   #cv2.imshow('blur', dst1)
cv2_imshow(dst2)   #cv2.imshow('sharp', dst2)

cv2.waitKey()             # 키가 눌려질때까지 기다리기
cv2.destroyAllWindows()

#### 실시간 영상 이미지에 필터값 적용
 [주의] 코랩에서는 오류발생함. PC 파이썬 환경에서 실행

In [ ]:
import sys
import cv2

def cartoon_filter(img):
    h, w = img.shape[:2]
    img2 = cv2.resize(img, (w//2, h//2))

    blr = cv2.bilateralFilter(img2, -1, 20, 7)
    edge = 255 - cv2.Canny(img2, 80, 120)
    edge = cv2.cvtColor(edge, cv2.COLOR_GRAY2BGR)

    dst = cv2.bitwise_and(blr, edge)
    dst = cv2.resize(dst, (w, h), interpolation=cv2.INTER_NEAREST)
    return dst


def pencil_sketch_filter(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    blr = cv2.GaussianBlur(gray, (0, 0), 3)
    dst = cv2.divide(gray, blr, scale=255)
    return dst

# 실시간 카메라 작동
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print('Video open failed!')
    sys.exit()

cam_mode = 0
while True:
    ret, frame = cap.read()
    if not ret:
        print('Video read failed!')
        break

    # 모드에 따라 필터 적용한 영상(frame) 보여주기
    if cam_mode == 1:
        frame = cartoon_filter(frame)
        title = f'{cam_mode} : cartoon_filter'
        tcolor = (255,0,255)
    elif cam_mode == 2:
        frame = pencil_sketch_filter(frame)
        title = f'{cam_mode} : pencil_sketch_filter'
        tcolor = (0,0,0)
    else:
        title = f'{cam_mode} :  '
        tcolor = (0,0,0)

    cv2.putText(frame, title, (30, 30),
            cv2.FONT_HERSHEY_DUPLEX, 1,
             tcolor, 2, cv2.LINE_AA)
    cv2.imshow('frame', frame)


    key = cv2.waitKey(1)
    if key==27: # ESC키 눌러졌을 때
        break
    elif key==ord(' '): #스페이스키 눌러졌을 때
        cam_mode += 1
        print(f'cam_mode:{cam_mode}')
        if cam_mode==3:
            cam_mode = 0

cap.release()
cv2.destroyAllWindows()
print('Video Finish!')

----------------------------

### [예제 2-17] 행렬의 합

In [ ]:
import numpy as np

A = np.array([[3,4],[5,0]])
B = np.array([[7,5],[4,-3]])

print(A + B)

### [예제 2-18] 행렬의 합

In [ ]:
A = np.array([[3,4,-1],[5,0,-2],[4,5,3]])
B = np.array([[5,6,7],[2,3,4],[1,8,9]])

print(A + B)
print(B + A)
print('행렬의 덧셈에 대한 교환법칙이 성립한다.')

### [예제 2-19] 스칼라 곱

In [ ]:
A = np.array([[5,-3,6],[4,7,1]])
c = 3

print(c * A)

### [예제 2-20] 행렬의 곱
- np.dot(A, B)
- 행렬의 곱은 사칙연산의 * 와 다른 @ 기호를 사용한다.

In [ ]:
A = np.array([[2,3],[2,4],[5,3]])
B = np.array([[4,3,-2],[2,3,1]])

print( np.dot(A, B) )
print( np.dot(B, A) )

In [ ]:
# A가 2x3이고, B가 2x3이면 행렬곱을 계산할 수 없다.
A = np.array([[2,3,-4],[1,2,3]])
B = np.array([[5,7,8],[4,6,1]])

print(A @ B)

### 특수 행렬
- numpy 행렬을 위한 참고 정보

|구분 |영문설명| numpy.함수명()|
|:---|:---|:---|
|대각행렬|Diagonal matrix | np.diag(x) |
|내적(행렬 곱)|Dot Product, Inner product| np.dot(a,b) , a @ b|
|대각합|Trace | np.trace(x)|
|행렬식|Matrix Deteminant  | np.linalg.det(x) |
|역행렬|Inverse of a matrix  | np.linalg.inv(x) |
|고유값, 고유벡터 |Eigenvalue, Eigenvector  | w, v = np.linalg.eig(x) |
|특이값 분해 |Singular value Decomposition  |u,s,vh = np.linalg.svd(A) |
|연립방정식 해 풀기 |Solve a linear matrix equation  | np.linalg.slove(a, b) |
|최소자승 해 풀기 |Compute the Least-squares solution  | m, c = np.linalg.lstsq(A,y,rcond=None)[0] |

#### 대각행렬
- 정방 행렬에서 주대각 원소를 제외한 나머지 원소(off-diagonal)가 모두 0인 행렬
- np.diag(x) 대각행렬의 원소 추출하는 함수

In [ ]:
matrix = np.array([[2,0,0],[0,3,0],[0,0,4]])

print( '행렬: \n',  matrix )
print( '대각행렬: ', np.diag(matrix) )     # 대각행렬 추출하기

In [ ]:
matrix = np.arange(9).reshape(3,3)

print( '행렬: \n',  matrix )               # 행렬
print( '대각행렬: ', np.diag(matrix) )     # 대각행렬 추출하기
print( '대각행렬: ', np.diag(matrix, k=1) )# k - start index

#### 단위 행렬
- 주대각 원소들은 모두 1을 갖고 나머지 원소들은 모두 0인 행렬

In [ ]:
np.identity(3, dtype=np.int8)  # 행이 3개인 단위 행렬

In [ ]:
np.eye(3, dtype=np.int8)

In [ ]:
np.eye(N=3, M=5, dtype=np.int8)

#### 스칼라 행렬
- 주대각 원소들이 모두 같은 값을 갖는 행렬

In [ ]:
np.eye(3, dtype=np.int8) * 3   # 단위행렬 x 스칼라값

#### 전치 행렬
- A가 임의의 𝐧×m 행렬일 때 A의 전치 행렬은 $𝐀^𝐓$로 표기하고 A의 행과 열을 바꾸어서 얻어진 m×n 행렬
- A.transpose()

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2,3],[4,5,6]])

print(A)  ; print('-'*10)
print(A.T); print('-'*10)
print(B)  ; print('-'*10)
print(B.T); print('-'*10)
print(B.transpose()); print('-'*10)

#### 상삼각 행렬

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9]])

#### 하삼각 행렬

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]])

#### 역행렬 :
- 정방행렬 A에 대해 AB=BA = I(단위행렬)



In [ ]:
A = np.array([[4,-7],[-1,2]])
B = np.linalg.inv(A)

print(A); print('-'*10)
print(B); print('-'*10)

[ 예제 2-25] 역행렬

In [ ]:
A = np.array([[2, 7],[1,4]])
B = np.array([[4,-7],[-1,2]])
B_ = np.linalg.inv(A)

print(A@B)
print(B@A)
print(B_ == B)

#### numpy 역행렬 확인하기

In [ ]:
from numpy.linalg import inv

A = np.array([[3,5],[2,3]])
Ainv = inv(A)

print( np.allclose(np.dot(A, Ainv), np.eye(2)) )
print( np.allclose(np.dot(Ainv, A), np.eye(2)) )

### [ 예제 2-27] 직교행렬 여부 판단하기
- 직교행렬 : $A^-1$ = $A^T$가 되는 행렬

In [18]:
from numpy.linalg import inv

A = np.array([[2,1],[3,2]])
Ainv = inv(A)
AT = A.T

print( np.allclose(Ainv, AT) )

False


### [예제 2-28]  부울행렬

In [ ]:
A = np.array([[1,0,1],[0,1,1],[1,1,0],[0,0,0]])
B = np.array([[1,1,0],[1,0,1],[0,0,1],[1,1,0]])


print(np.logical_or(A, B).astype(int)  )   # 논리합
print(np.logical_and(A, B).astype(int)  )  # 논리곱


### 행렬식 구하기 :determinant
- 행렬 A의 행렬식이란 정방행렬 A에 고유한 수치를 대응시키는 것, 
- A의 행렬식을 |A| or det(A)
- $det(\begin{vmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{vmatrix})$ = $a_{11}a_{22} - a_{12}a_{21}$

In [13]:
import numpy as np

A = np.array([[3,2],[4,6]], dtype=np.int8)
result = np.linalg.det(A)

print(A)
print(np.int8(result))

[[3 2]
 [4 6]]
10


In [17]:
A = np.array([[5,2,0],
              [3,7,2],
              [0,1,3]], dtype=np.int8)
result = np.linalg.det(A)
print(A)
print(result)

[[5 2 0]
 [3 7 2]
 [0 1 3]]
76.99999999999996
